name: "Terraform Infrastructure"

on:
  # main 브랜치 인프라 변경 시 실행
  push:
    branches: ["main"]

    paths:
      - "infra/terraform/live/prod/**"
      - "infra/terraform/global/**"
      - ".github/workflows/terraform-prod.yml" # 테스트용

  # main 대상 PR에서 plan 검증
  pull_request:
    branches: ["main"]
    paths:
      - "infra/terraform/live/prod/**"
      - "infra/terraform/global/**"
      - ".github/workflows/terraform-prod.yml" # 테스트용

permissions:
  contents: read # 소스 코드 읽기 권한
  id-token: write # JWT 토큰 발급 권한

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra/terraform/live/prod/

    steps:
      # 1) 코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Terraform CLI 준비
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      # 2-1) AWS 인증 (OIDC AssumeRole)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GHA_TERRAFORM_ROLE_ARN }}
          role-session-name: github-actions-tf-prod
          aws-region: ap-northeast-2
        
      # 3) 초기화 (backend/provider/module 다운로드)
      - name: Terraform Init
        run: terraform init
      
      # 4) PR에서는 Plan으로 변경사항 검증
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_discord_webhook_url: ${{ secrets.TF_VAR_DISCORD_WEBHOOK_URL }}
          TF_VAR_grafana_admin_password: ${{ secrets.TF_VAR_GRAFANA_ADMIN_PASSWORD }}
          TF_VAR_alb_verify_secret: ${{ secrets.TF_VAR_ALB_VERIFY_SECRET }}
          TF_VAR_MAIL_PASSWORD: ${{ secrets.TF_VAR_MAIL_PASSWORD }}
          TF_VAR_kakao_client_secret: ${{ secrets.TF_VAR_KAKAO_CLIENT_SECRET }}
          TF_VAR_kakao_client_id: ${{ secrets.TF_VAR_KAKAO_CLIENT_ID }}
          TF_VAR_jwt_secret: ${{ secrets.TF_VAR_JWT_SECRET }}
          TF_VAR_mail_from: ${{ secrets.TF_VAR_MAIL_FROM }}
          TF_VAR_mail_username: ${{ secrets.TF_VAR_MAIL_USERNAME }}
          TF_VAR_bus_api_key: ${{ secrets.TF_VAR_BUS_API_KEY }}
          TF_VAR_bus_api_key_encoded: ${{ secrets.TF_VAR_BUS_API_KEY_ENCODED }}
        run: terraform plan -no-color

      # 5) main push에서는 Apply 실행
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_discord_webhook_url: ${{ secrets.TF_VAR_DISCORD_WEBHOOK_URL }}
          TF_VAR_grafana_admin_password: ${{ secrets.TF_VAR_GRAFANA_ADMIN_PASSWORD }}
          TF_VAR_alb_verify_secret: ${{ secrets.TF_VAR_ALB_VERIFY_SECRET }}
          TF_VAR_MAIL_PASSWORD: ${{ secrets.TF_VAR_MAIL_PASSWORD }}
          TF_VAR_kakao_client_secret: ${{ secrets.TF_VAR_KAKAO_CLIENT_SECRET }}
          TF_VAR_kakao_client_id: ${{ secrets.TF_VAR_KAKAO_CLIENT_ID }}
          TF_VAR_jwt_secret: ${{ secrets.TF_VAR_JWT_SECRET }}
          TF_VAR_mail_from: ${{ secrets.TF_VAR_MAIL_FROM }}
          TF_VAR_mail_username: ${{ secrets.TF_VAR_MAIL_USERNAME }}
          TF_VAR_bus_api_key: ${{ secrets.TF_VAR_BUS_API_KEY }}
          TF_VAR_bus_api_key_encoded: ${{ secrets.TF_VAR_BUS_API_KEY_ENCODED }}
        run: terraform apply -auto-approve
